version: "3.8"
services:
  webapp:
    container_name: mangojelly_back
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mango_jelly?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: ssafy
#      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
#      SPRING_DATA_MONGODB_HOST: mongodb
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_USERNAME: root
#      SPRING_DATA_MONGODB_PASSWORD: ssafy
#      SPRING_DATA_MONGODB_DATABASE: mango_jelly
#      SPRING_REDIS_HOST: redis-16839.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
#      SPRING_REDIS_PORT: 16839
#      SRPING_REDIS_PASSWORD: jBysS5BNbbAWxICOk1FrpcvrTSgiufXq
#      CLOUD_AWS_S3_BUCKET: mongo-jelly
#      CLOUD_AWS_STACK_AUTO: false
#      CLOUD_AWS_REGION_STATIC: ap-northeast-2
#      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: AKIARY35WC7HBSAEI46H
#      CLOUD_AWS_CREDENTIALS_SECRET_KEY: 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
#      JWT_SECRET_KEY: "qwaessrxftgfcghy2hb3ji4kjn5ogygvuhboknkpllk1k23456o5k4n32knkknklmlmlhhuhbiknk2l3m456m44jigtdrsesrdxygvvhj3n45lk6ml8e2srfdx4yhg56ujnbn7kmn9klkm"

    networks:
      - mango-jelly_mango-net
      
networks:
  mango-jelly_mango-net:
    driver: bridge
    external: true
